default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test_backend_development

production:
  adapter: postgresql
  encoding: unicode
  database: your_production_database
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5432                              
  cache:
    database: test_backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    database: test_backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    database: test_backend_production_cable
    migrations_paths: db/cable_migrate
