default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test_backend_development

production:
  <<: *default
  database: test_backend_development_djun  # Database name from Render
  username: test_backend_development       # Username from Render
  password: <%= ENV["TEST_BACKEND_DATABASE_PASSWORD"] %>  # Use your password from Render
  host: <%= ENV["DATABASE_HOST"] %>        # Use DATABASE_HOST from environment variables
  port: 5432                              # Default PostgreSQL port
